import { z } from "zod";

const normalizedRectSchema = z.object({
  x: z.number().min(0).max(1),
  y: z.number().min(0).max(1),
  width: z.number().positive().max(1),
  height: z.number().positive().max(1),
}).refine((value) => value.x + value.width <= 1 && value.y + value.height <= 1, {
  message: "Normalized rectangle must stay inside the composition",
});

export const deliveryProfileSchema = z.object({
  schemaVersion: z.literal(1),
  id: z.enum([
    "instagram-reel",
    "tiktok",
    "youtube-short",
    "youtube-landscape",
    "instagram-square",
    "instagram-portrait",
    "custom",
  ]),
  label: z.string().min(1).max(100),
  platform: z.enum(["instagram", "tiktok", "youtube", "generic"]),
  width: z.number().int().min(1).max(7680),
  height: z.number().int().min(1).max(7680),
  fps: z.number().int().min(1).max(120),
  orientation: z.enum(["portrait", "landscape", "square"]),
  actionSafe: normalizedRectSchema,
  titleSafe: normalizedRectSchema,
  captionSafe: normalizedRectSchema,
  uiOcclusionZones: z.array(z.object({
    id: z.string().min(1),
    label: z.string().min(1),
    rect: normalizedRectSchema,
    severity: z.enum(["info", "warning", "blocking"]),
  })).max(20),
});

const projectSettingsFields = {
  width: z.number().int().min(1).max(7680),
  height: z.number().int().min(1).max(7680),
  fps: z.number().int().min(1).max(120),
  duration: z.number().min(0),
  backgroundColor: z.string(),
  sampleRate: z.number().int(),
  deliveryProfile: deliveryProfileSchema.optional(),
};

export const createProjectSchema = z.object({
  name: z.string().min(1, "Project name is required").max(200),
  settings: z
    .object({
      ...projectSettingsFields,
      width: projectSettingsFields.width.default(1920),
      height: projectSettingsFields.height.default(1080),
      fps: projectSettingsFields.fps.default(30),
      duration: projectSettingsFields.duration.default(0),
      backgroundColor: projectSettingsFields.backgroundColor.default("#000000"),
      sampleRate: projectSettingsFields.sampleRate.default(44100),
    })
    .optional(),
});

export const transitionSchema = z.object({
  id: z.string().min(1),
  trackId: z.string().min(1),
  clipAId: z.string().min(1),
  clipBId: z.string().min(1),
  duration: z.number().positive().max(30),
  type: z.string().min(1),
  params: z.record(z.union([z.number(), z.string(), z.boolean()])).default({}),
});

/** Nested sequence library entry (precomp). Depth-1 content validated in editor-core. */
export const sequenceSchema = z.object({
  id: z.string().min(1),
  name: z.string().min(1).max(200),
  tracks: z.array(z.unknown()),
  transitions: z.array(transitionSchema).default([]),
  durationHint: z.number().min(0).optional(),
});

/**
 * Nest clips use sourceSequenceId and must not carry media/text/shape content.
 * Enforced in editor-core validateSequences; this helper is for API/UI checks.
 */
export function isNestClipPayload(clip: {
  sourceSequenceId?: string | null;
  sourceMediaId?: string | null;
  textParams?: unknown;
  shapeParams?: unknown;
}): boolean {
  return Boolean(clip.sourceSequenceId);
}

export const maskSchema = z.object({
  shape: z.enum(["rect", "ellipse"]),
  x: z.number().min(0).max(1),
  y: z.number().min(0).max(1),
  width: z.number().min(0).max(1),
  height: z.number().min(0).max(1),
  feather: z.number().min(0).max(0.5),
  inverted: z.boolean(),
  opacity: z.number().min(0).max(1),
});

export const adjustmentLayerSchema = z.object({
  target: z.literal("below"),
});

/** Compositing relationship persisted on a clip. */
export const trackMatteSchema = z.object({
  sourceClipId: z.string().min(1),
  type: z.enum(["alpha", "luma"]),
  refinement: z.object({
    threshold: z.number().min(0).max(1),
    feather: z.number().min(0).max(0.5),
    inverted: z.boolean(),
  }).optional(),
});

/** Editable inverse camera-motion correction generated by optical flow. */
export const stabilizationSchema = z.object({
  enabled: z.boolean(),
  samples: z.array(z.object({
    time: z.number().min(0),
    x: z.number().min(0).max(1),
    y: z.number().min(0).max(1),
    scale: z.number().positive().optional(),
    rotation: z.number().optional(),
    confidence: z.number().min(0).max(1).optional(),
  })).min(2),
  smoothness: z.number().min(0).max(1),
  cropScale: z.number().min(1).max(1.5),
});

export const cropSchema = z.object({
  x: z.number().min(0).max(1),
  y: z.number().min(0).max(1),
  width: z.number().positive().max(1),
  height: z.number().positive().max(1),
}).refine((crop) => crop.x + crop.width <= 1 && crop.y + crop.height <= 1, {
  message: "Crop bounds must stay inside the source",
});

export const mediaLayoutSchema = z.object({
  schemaVersion: z.literal(1),
  fit: z.enum(["cover", "contain", "fill", "none"]),
  /** Destination cell in normalized composition coordinates. */
  viewport: normalizedRectSchema.optional(),
  focalPoint: z.object({
    x: z.number().min(0).max(1),
    y: z.number().min(0).max(1),
  }).optional(),
});

/** Schema for the shared `color-grade` effect's partial params payload. */
export const primaryColorGradeSchema = z.object({
  exposure: z.number().finite().min(-4).max(4).optional(),
  contrast: z.number().finite().min(-100).max(100).optional(),
  saturation: z.number().finite().min(-100).max(100).optional(),
  temperature: z.number().finite().min(-100).max(100).optional(),
  tint: z.number().finite().min(-100).max(100).optional(),
  shadows: z.number().finite().min(-100).max(100).optional(),
  highlights: z.number().finite().min(-100).max(100).optional(),
  blacks: z.number().finite().min(-100).max(100).optional(),
  whites: z.number().finite().min(-100).max(100).optional(),
  vibrance: z.number().finite().min(-100).max(100).optional(),
}).strict();

/** Schema for the `hsl-secondary` effect's partial qualifier/correction payload. */
export const hslSecondarySchema = z.object({
  hueCenter: z.number().finite().min(0).max(360).optional(),
  hueRange: z.number().finite().min(1).max(180).optional(),
  saturationMin: z.number().finite().min(0).max(1).optional(),
  saturationMax: z.number().finite().min(0).max(1).optional(),
  lightnessMin: z.number().finite().min(0).max(1).optional(),
  lightnessMax: z.number().finite().min(0).max(1).optional(),
  feather: z.number().finite().min(0).max(1).optional(),
  hueShift: z.number().finite().min(-180).max(180).optional(),
  saturationShift: z.number().finite().min(-100).max(100).optional(),
  lightnessShift: z.number().finite().min(-100).max(100).optional(),
  mix: z.number().finite().min(0).max(1).optional(),
}).strict().superRefine((value, context) => {
  if (value.saturationMin != null && value.saturationMax != null && value.saturationMin > value.saturationMax) {
    context.addIssue({ code: z.ZodIssueCode.custom, path: ["saturationMin"], message: "Saturation minimum cannot exceed maximum" });
  }
  if (value.lightnessMin != null && value.lightnessMax != null && value.lightnessMin > value.lightnessMax) {
    context.addIssue({ code: z.ZodIssueCode.custom, path: ["lightnessMin"], message: "Lightness minimum cannot exceed maximum" });
  }
});

/** Schema for partial `lift-gamma-gain` color wheel controls. */
export const liftGammaGainSchema = z.object({
  liftRed: z.number().finite().min(-1).max(1).optional(),
  liftGreen: z.number().finite().min(-1).max(1).optional(),
  liftBlue: z.number().finite().min(-1).max(1).optional(),
  liftMaster: z.number().finite().min(-1).max(1).optional(),
  gammaRed: z.number().finite().min(-1).max(1).optional(),
  gammaGreen: z.number().finite().min(-1).max(1).optional(),
  gammaBlue: z.number().finite().min(-1).max(1).optional(),
  gammaMaster: z.number().finite().min(-1).max(1).optional(),
  gainRed: z.number().finite().min(-1).max(1).optional(),
  gainGreen: z.number().finite().min(-1).max(1).optional(),
  gainBlue: z.number().finite().min(-1).max(1).optional(),
  gainMaster: z.number().finite().min(-1).max(1).optional(),
}).strict();

/** Schema for a partial `levels` effect payload. */
export const levelsSchema = z.object({
  inputBlack: z.number().finite().min(0).max(1).optional(),
  inputWhite: z.number().finite().min(0).max(1).optional(),
  gamma: z.number().finite().min(0.1).max(10).optional(),
  outputBlack: z.number().finite().min(0).max(1).optional(),
  outputWhite: z.number().finite().min(0).max(1).optional(),
}).strict().superRefine((value, context) => {
  if (value.inputBlack != null && value.inputWhite != null && value.inputBlack >= value.inputWhite) {
    context.addIssue({ code: z.ZodIssueCode.custom, path: ["inputBlack"], message: "Input black must be below input white" });
  }
  if (value.outputBlack != null && value.outputWhite != null && value.outputBlack >= value.outputWhite) {
    context.addIssue({ code: z.ZodIssueCode.custom, path: ["outputBlack"], message: "Output black must be below output white" });
  }
});

export const curvePointsSchema = z.array(
  z.object({
    x: z.number().finite().min(0).max(1),
    y: z.number().finite().min(0).max(1),
  })
).min(2).max(8).superRefine((points, context) => {
  if (points[0]?.x !== 0 || points[points.length - 1]?.x !== 1) {
    context.addIssue({ code: z.ZodIssueCode.custom, message: "Curve must begin at x=0 and end at x=1" });
  }
  for (let index = 1; index < points.length; index++) {
    if (points[index]!.x <= points[index - 1]!.x) {
      context.addIssue({ code: z.ZodIssueCode.custom, message: "Curve x values must be strictly increasing" });
      break;
    }
  }
});

export const colorCurvesSchema = z.object({
  luma: curvePointsSchema.optional(),
  red: curvePointsSchema.optional(),
  green: curvePointsSchema.optional(),
  blue: curvePointsSchema.optional(),
}).strict();

export const updateProjectSchema = z.object({
  name: z.string().min(1).max(200).optional(),
  settings: z
    .object({
      width: projectSettingsFields.width.optional(),
      height: projectSettingsFields.height.optional(),
      fps: projectSettingsFields.fps.optional(),
      duration: projectSettingsFields.duration.optional(),
      backgroundColor: projectSettingsFields.backgroundColor.optional(),
      sampleRate: projectSettingsFields.sampleRate.optional(),
      deliveryProfile: projectSettingsFields.deliveryProfile,
    })
    .optional(),
  data: z.record(z.unknown()).optional(),
});

export type CreateProjectInput = z.infer<typeof createProjectSchema>;
export type UpdateProjectInput = z.infer<typeof updateProjectSchema>;
export type TransitionInput = z.infer<typeof transitionSchema>;
export type SequenceInput = z.infer<typeof sequenceSchema>;
export type PrimaryColorGradeInput = z.infer<typeof primaryColorGradeSchema>;
export type HslSecondaryInput = z.infer<typeof hslSecondarySchema>;
export type LiftGammaGainInput = z.infer<typeof liftGammaGainSchema>;
export type LevelsInput = z.infer<typeof levelsSchema>;
export type ColorCurvesInput = z.infer<typeof colorCurvesSchema>;
export type TrackMatteInput = z.infer<typeof trackMatteSchema>;
export type StabilizationInput = z.infer<typeof stabilizationSchema>;
